In [ ]:
import csv 
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.model_selection import train_test_split

#   traitestsplit

In [29]:
sampled_dff = pd.get_dummies(df)

X = sampled_dff.drop('cardio', axis=1)
y = sampled_dff['cardio']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

#   Standarisation

In [30]:
from sklearn.preprocessing import StandardScaler


sc = StandardScaler()


X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

#   Smote

In [31]:
from imblearn.over_sampling import SMOTE


smote = SMOTE(sampling_strategy='auto', random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

#   xgboost

In [32]:
import xgboost as xgb
from xgboost import XGBClassifier

xgb_classifier = XGBClassifier()
xgb_classifier.fit(X_train, y_train)

y_pred = xgb_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

confusion_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion_mat)

class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

c:\Users\LENOVO\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\data.py:335: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
c:\Users\LENOVO\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\data.py:338: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  is_categorical_dtype(dtype) or is_pa_ext_categorical_dtype(dtype)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\data.py:384: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype):
c:\Users\LENOVO\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\data.py:359: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future vers

Accuracy: 0.72
Confusion Matrix:
[[3817 1158]
 [1539 3286]]
Classification Report:
              precision    recall  f1-score   support

           0       0.71      0.77      0.74      4975
           1       0.74      0.68      0.71      4825

    accuracy                           0.72      9800
   macro avg       0.73      0.72      0.72      9800
weighted avg       0.73      0.72      0.72      9800



c:\Users\LENOVO\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\data.py:335: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
c:\Users\LENOVO\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\data.py:338: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  is_categorical_dtype(dtype) or is_pa_ext_categorical_dtype(dtype)
c:\Users\LENOVO\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\data.py:384: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype):
c:\Users\LENOVO\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\data.py:359: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future vers

#   random forest

In [33]:
rf_classifier = RandomForestClassifier()
rf_classifier.fit(X_train, y_train)

y_pred = rf_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

confusion_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion_mat)

class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)


Accuracy: 0.70
Confusion Matrix:
[[3536 1439]
 [1475 3350]]
Classification Report:
              precision    recall  f1-score   support

           0       0.71      0.71      0.71      4975
           1       0.70      0.69      0.70      4825

    accuracy                           0.70      9800
   macro avg       0.70      0.70      0.70      9800
weighted avg       0.70      0.70      0.70      9800



#   logestic regressor 


In [34]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()


model.fit(X_train, y_train)
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

confusion_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion_mat)

class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

Accuracy: 0.73
Confusion Matrix:
[[3888 1087]
 [1596 3229]]
Classification Report:
              precision    recall  f1-score   support

           0       0.71      0.78      0.74      4975
           1       0.75      0.67      0.71      4825

    accuracy                           0.73      9800
   macro avg       0.73      0.73      0.72      9800
weighted avg       0.73      0.73      0.73      9800



c:\Users\LENOVO\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


#   logestic regression + ridge

In [35]:
model_ridge = LogisticRegression(penalty='l2', C=1.5)  # Vous pouvez ajuster la valeur de C pour le niveau de régularisation

# Entraîner le modèle Ridge sur les données d'entraînement
model_ridge.fit(X_train, y_train)

# Faire des prédictions sur les données de test
y_pred_ridge = model_ridge.predict(X_test)

accuracy = accuracy_score(y_test, y_pred_ridge)
print(f"Accuracy: {accuracy:.2f}")

confusion_mat = confusion_matrix(y_test, y_pred_ridge)
print("Confusion Matrix:")
print(confusion_mat)

class_report = classification_report(y_test, y_pred_ridge)
print("Classification Report:")
print(class_report)

Accuracy: 0.72
Confusion Matrix:
[[3775 1200]
 [1564 3261]]
Classification Report:
              precision    recall  f1-score   support

           0       0.71      0.76      0.73      4975
           1       0.73      0.68      0.70      4825

    accuracy                           0.72      9800
   macro avg       0.72      0.72      0.72      9800
weighted avg       0.72      0.72      0.72      9800



c:\Users\LENOVO\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


#   LogisticRegression +lasso

In [36]:
model_lasso = LogisticRegression(penalty='l1', C=1.5, solver='liblinear')  # Vous pouvez ajuster la valeur de C pour le niveau de régularisation

# Entraîner le modèle Lasso sur les données d'entraînement
model_lasso.fit(X_train, y_train)

# Faire des prédictions sur les données de test
y_pred_lasso = model_lasso.predict(X_test)

accuracy = accuracy_score(y_test, y_pred_lasso)
print(f"Accuracy: {accuracy:.2f}")

confusion_mat = confusion_matrix(y_test, y_pred_lasso)
print("Confusion Matrix:")
print(confusion_mat)

class_report = classification_report(y_test, y_pred_lasso)
print("Classification Report:")
print(class_report)

Accuracy: 0.73
Confusion Matrix:
[[3905 1070]
 [1579 3246]]
Classification Report:
              precision    recall  f1-score   support

           0       0.71      0.78      0.75      4975
           1       0.75      0.67      0.71      4825

    accuracy                           0.73      9800
   macro avg       0.73      0.73      0.73      9800
weighted avg       0.73      0.73      0.73      9800



In [39]:
sampled_dff['cardio'].mean()


0.4987755102040816

#   Lr+ smote

In [40]:
model_lasso = LogisticRegression(penalty='l1', C=1.5, solver='liblinear')  # Vous pouvez ajuster la valeur de C pour le niveau de régularisation

# Entraîner le modèle Lasso sur les données d'entraînement
model_lasso.fit(X_train_resampled, y_train_resampled )

# Faire des prédictions sur les données de test
y_pred_lasso = model_lasso.predict(X_test)

accuracy = accuracy_score(y_test, y_pred_lasso)
print(f"Accuracy: {accuracy:.2f}")

confusion_mat = confusion_matrix(y_test, y_pred_lasso)
print("Confusion Matrix:")
print(confusion_mat)

class_report = classification_report(y_test, y_pred_lasso)
print("Classification Report:")
print(class_report)

Accuracy: 0.73
Confusion Matrix:
[[3909 1066]
 [1580 3245]]
Classification Report:
              precision    recall  f1-score   support

           0       0.71      0.79      0.75      4975
           1       0.75      0.67      0.71      4825

    accuracy                           0.73      9800
   macro avg       0.73      0.73      0.73      9800
weighted avg       0.73      0.73      0.73      9800



In [41]:
model_ridge = LogisticRegression(penalty='l2', C=1.5)  # Vous pouvez ajuster la valeur de C pour le niveau de régularisation

# Entraîner le modèle Ridge sur les données d'entraînement
model_ridge.fit(X_train_sc , y_train)

# Faire des prédictions sur les données de test
y_pred_ridge = model_ridge.predict(X_test_sc )

accuracy = accuracy_score(y_test, y_pred_ridge)
print(f"Accuracy: {accuracy:.2f}")

confusion_mat = confusion_matrix(y_test, y_pred_ridge)
print("Confusion Matrix:")
print(confusion_mat)

class_report = classification_report(y_test, y_pred_ridge)
print("Classification Report:")
print(class_report)

Accuracy: 0.73
Confusion Matrix:
[[3903 1072]
 [1580 3245]]
Classification Report:
              precision    recall  f1-score   support

           0       0.71      0.78      0.75      4975
           1       0.75      0.67      0.71      4825

    accuracy                           0.73      9800
   macro avg       0.73      0.73      0.73      9800
weighted avg       0.73      0.73      0.73      9800

