In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

In [2]:
import csv 
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.model_selection import train_test_split

In [7]:
data=pd.read_csv('datas/data1.csv')

In [8]:
data.head()

Age  Gender      Height     Weight  Blood Type        BMI  Temperature  \
0  22.0       0  174.899914  69.979384           0  22.876571    97.987387   
1  26.0       1  184.917386  84.928715           3  24.836996    98.252387   
2  31.0       1  194.904978  69.274302           1  18.235862    98.599654   
3  26.0       1  170.592294  53.457002           2  18.369011    98.822864   
4  31.0       0  179.538738  77.071192           2  23.909789    98.232003   

   Heart Rate  Blood Pressure  Cholesterol  Diabetes  Smoking  
0        91.0           125.0        127.0         1        1  
1        71.0           133.0        228.0         1        0  
2        94.0           100.0        212.0         1        1  
3        75.0           113.0        234.0         1        1  
4        60.0           126.0        217.0         1        0

In [9]:
data.shape

(131249, 12)

In [11]:
sampled_dff = pd.get_dummies(data)

X = sampled_dff.drop('Diabetes', axis=1)
y = sampled_dff['Diabetes']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

# SMOTE


In [12]:
from imblearn.over_sampling import SMOTE


smote = SMOTE(sampling_strategy='auto', random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

#   xgboost

In [13]:
import xgboost as xgb
from xgboost import XGBClassifier

xgb_classifier = XGBClassifier()
xgb_classifier.fit(X_train, y_train)

y_pred = xgb_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

confusion_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion_mat)

class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

c:\Users\Wiem\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\data.py:335: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
c:\Users\Wiem\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\data.py:338: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  is_categorical_dtype(dtype) or is_pa_ext_categorical_dtype(dtype)
c:\Users\Wiem\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\data.py:384: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype):
c:\Users\Wiem\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\data.py:359: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use

Accuracy: 0.90
Confusion Matrix:
[[   12  2576]
 [   12 23650]]
Classification Report:
              precision    recall  f1-score   support

           0       0.50      0.00      0.01      2588
           1       0.90      1.00      0.95     23662

    accuracy                           0.90     26250
   macro avg       0.70      0.50      0.48     26250
weighted avg       0.86      0.90      0.86     26250



c:\Users\Wiem\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\data.py:335: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
c:\Users\Wiem\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\data.py:338: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  is_categorical_dtype(dtype) or is_pa_ext_categorical_dtype(dtype)
c:\Users\Wiem\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\data.py:384: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype):
c:\Users\Wiem\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\data.py:359: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use

#   randonforest

In [14]:
rf_classifier = RandomForestClassifier()
rf_classifier.fit(X_train_resampled, y_train_resampled)

y_pred = rf_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

confusion_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion_mat)

class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

Accuracy: 0.88
Confusion Matrix:
[[  739  1849]
 [ 1367 22295]]
Classification Report:
              precision    recall  f1-score   support

           0       0.35      0.29      0.31      2588
           1       0.92      0.94      0.93     23662

    accuracy                           0.88     26250
   macro avg       0.64      0.61      0.62     26250
weighted avg       0.87      0.88      0.87     26250



#   logestic regression + ridge

In [15]:
from sklearn.linear_model import LogisticRegression
model_ridge = LogisticRegression(penalty='l2', C=1.5)  


model_ridge.fit(X_train_resampled, y_train_resampled)

y_pred_ridge = model_ridge.predict(X_test)

accuracy = accuracy_score(y_test, y_pred_ridge)
print(f"Accuracy: {accuracy:.2f}")

confusion_mat = confusion_matrix(y_test, y_pred_ridge)
print("Confusion Matrix:")
print(confusion_mat)

class_report = classification_report(y_test, y_pred_ridge)
print("Classification Report:")
print(class_report)

Accuracy: 0.57
Confusion Matrix:
[[ 1038  1550]
 [ 9612 14050]]
Classification Report:
              precision    recall  f1-score   support

           0       0.10      0.40      0.16      2588
           1       0.90      0.59      0.72     23662

    accuracy                           0.57     26250
   macro avg       0.50      0.50      0.44     26250
weighted avg       0.82      0.57      0.66     26250



c:\Users\Wiem\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
